### ISSUE TITLE
Link monitoring

### ISSUE THREAD

**Issue by kokoronikui** [LivingWithHippos/unchained-android#135] opened 2021-07-12 04:39 UTC
Can you give an ETA on when link monitoring will be added? While torrent packs with multiple files can be individually accessed but all the files inside the torrent appear in RD's download list. Is it possible to only display the file that's currently being accessed? CHD so far is capable of doing that. A fully compatible Android TV version would also be nice

**Comment by LivingWithHippos** [comment] 2021-07-12 07:23
This is how it works in Real Debrid, it's not clear to me what do you mean with
> only display the file that's currently being accessed
can you elaborate?

**Comment by LivingWithHippos** [comment] 2021-09-27 07:53
Duplicate of #31

**Closed by LivingWithHippos** 2021-09-27 07:53 UTC
