### ISSUE TITLE
Open Shared Holster Link

### ISSUE THREAD

**Issue by Cueball666uk** [LivingWithHippos/unchained-android#60] opened 2020-10-07 14:38 UTC
If I try and open a hosted link by long clicking in chrome and "share with" Unchained, It takes me to the User tab not the new download tab and it also doesn't initiate the download either. The "original" app has this feature and I would love to see this come across to Unchained. Thanks you so much 🙂👍🏻

**Comment by LivingWithHippos** [comment] 2020-10-07 14:48
Thanks for the feedback; I'll close this since it's a duplicate of #20. You can follow that to get notified of when I add it. It's going to be the next thing I add anyway.

**Closed by LivingWithHippos** 2020-10-07 14:48 UTC
