### ISSUE TITLE
[FEATURE REQUEST] Download button does not show location chooser

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#202] opened 2022-04-22 21:40 UTC
If you press on the download button, it only is able to download to internal storage. There is no location chooser to download to external micro SD or other folders. 

![Screenshot_20220422-234205_Unchained](https://user-images.githubusercontent.com/20338545/164799548-677893a3-7812-4af5-b437-c7b3cdb31ada.jpg)

**Comment by LivingWithHippos** [comment] 2022-04-23 09:01
duplicate of #105

**Closed by LivingWithHippos** 2022-04-23 09:01 UTC
Labels: enhancement

**Comment by Invictaz** [comment] 2022-04-25 14:19
Not a duplicate. Location chooser can also point to a specific location on the internal SD card.

**Comment by LivingWithHippos** [comment] 2022-04-25 14:30
Right now the downloader uses the internal memory because the default Android downloader allows only that (unless I've been missing something). When I implement the download on sd card stuff I'll allow downloading on any folder, not just on the external sd
