### ISSUE TITLE
[FEATURE REQUEST] Sort downloads

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#204] opened 2022-04-22 22:51 UTC
Add the ability invert sorting. Or sort based on name, size etc. 

Now its based on what is added last. This gives
Ep10
Ep9
Ep8
Etc

Instead of
Ep8
Ep9
Ep10

![Screenshot_20220423-004837_Unchained](https://user-images.githubusercontent.com/20338545/164814688-c55be653-5e2e-4842-b24b-939a0fa95e26.jpg)

**Comment by LivingWithHippos** [comment] 2022-04-23 09:00
Duplicate of #113

**Closed by LivingWithHippos** 2022-04-23 09:00 UTC
Labels: enhancement
